// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx9QehE8H7d0psV7f0vlpqk8_ympgutS0',
    appId: '1:848097395615:web:a7e5c38bee9767f71433aa',
    messagingSenderId: '848097395615',
    projectId: 'instructor-beats-13db1',
    authDomain: 'instructor-beats-13db1.firebaseapp.com',
    storageBucket: 'instructor-beats-13db1.firebasestorage.app',
    measurementId: 'G-37PJBFVPS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHWKltT5Ve6bHs-I2NrvTIoh5Pe1o45Ow',
    appId: '1:848097395615:android:af9c513f4e8e9c7e1433aa',
    messagingSenderId: '848097395615',
    projectId: 'instructor-beats-13db1',
    storageBucket: 'instructor-beats-13db1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIqeGnG3cguDgAbE5ORL8gszWMnaTUmTI',
    appId: '1:848097395615:ios:031a072910cca6e71433aa',
    messagingSenderId: '848097395615',
    projectId: 'instructor-beats-13db1',
    storageBucket: 'instructor-beats-13db1.firebasestorage.app',
    iosBundleId: 'com.example.instructorBeatsAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIqeGnG3cguDgAbE5ORL8gszWMnaTUmTI',
    appId: '1:848097395615:ios:031a072910cca6e71433aa',
    messagingSenderId: '848097395615',
    projectId: 'instructor-beats-13db1',
    storageBucket: 'instructor-beats-13db1.firebasestorage.app',
    iosBundleId: 'com.example.instructorBeatsAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx9QehE8H7d0psV7f0vlpqk8_ympgutS0',
    appId: '1:848097395615:web:837e97b43252fb151433aa',
    messagingSenderId: '848097395615',
    projectId: 'instructor-beats-13db1',
    authDomain: 'instructor-beats-13db1.firebaseapp.com',
    storageBucket: 'instructor-beats-13db1.firebasestorage.app',
    measurementId: 'G-Y3ESP01NL9',
  );

}